version: "3"
services:
  db2:
    # image: ibmcom/db2:11.5.5.1
    image: db2:11.5.5.1
    # build:
    #   context: "./db2"
    ports:
      - "50002:50000"
    env_file: 
      - ${PWD}/db2/.env
    # environment:
    #   - DB2INST1_PASSWORD=pa55w0rd
    #   - LICENSE=accept
    # volumes:
    #   - ${PWD}/database:/database
    networks:
      - db2-net

  go:
    image: go-db2:buster
    # build:
    #   context: "./go"
    depends_on:
      - db2
    environment:
      - DB2DSN=HOSTNAME=db2;DATABASE=testdb;PORT=50002;PROTOCOL=TCPIP;UID=db2inst1;PWD=pa55w0rd
    networks:
      - db2-net

  # was:
  #   build:
  #     context: "./was"
  #   ports:
  #     - "9043:9043"
  #     - "9443:9443"
  #     - "9080:9080"    
  #   depends_on:
  #     - db2
  #   # volumes:
  #   #   - ${PWD}/db2-driver:/db2
  #   networks:
  #     - db2-net

# volumes:
#   db2-driver: 

networks:
  db2-net:
    driver: bridge
